# Copyright (C) 2022 Ra√∫l Wolters
#
# This file is part of rustronomy.
#
# rustronomy is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# rustronomy is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with rustronomy.  If not, see <http://www.gnu.org/licenses/>.

# Why 2 space tabs? Rust requires so much indentation that 4 space tabs often
# restrict the length of code that fits on one line.
#
# 2 space tabs are not a formal requirement for rustfmt, crate authors can use
# whatever they like, as long as they do so through configuring rustfmt
tab_spaces = 2

#allow for one-liners to take up a full line
use_small_heuristics = "Max"